version: "3.8"

services:
    backend:
        container_name: ${SERVICE_CONTAINER_NAME}
        build:
            context: .
            dockerfile: src/Dockerfile
        env_file:
            - .env
        ports:
            - ${SERVICE_PORT}:${SERVICE_PORT}
        restart: always
